### ISSUE TITLE
mongodb数据库架构是什么样的呢

### ISSUE THREAD

**Issue by Jamalmo** [jax777/scan_monitor#1]
看文档没写mongodb数据的架构是什么样，不知道怎么建表，没法复现出来，还有不知道能不能手工更新listip，然后达到监测端口的作用

**Comment by jax777** [comment]
mongo不用自己建表，只要用docker把mongo开起来，运行之后程序自然会吧mongo里没有的collection建立起来。
好久以前写的了 当时就写了添加域名，用来辅助刷src的，手工更新listip没写，你可以搭起来看数据库就行。

**Comment by Jamalmo** [comment]
我是没用docker，我就是纯粹的跑的一个mongodb，你说的那个docker的地址是哪个呢，我能不能把docker里面的数据库配置导出来，弄到我本地跑的mongodb上面，然后去跑
